name: Zig CI
on:
  push:
    branches:
      - main
    paths:
      - 'src/**/*.zig'
      - 'build.zig'
      - 'build.zig.zon'
  pull_request:
    paths:
      - 'src/**/*.zig'
      - 'build.zig'
      - 'build.zig.zon'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - uses: actions/cache@v4
        id: gl-xml
        env:
          cache-name: cache-gl-xml
        with:
          path: gl.xml
          key: ${{ runner.os }}-build-${{ env.cache-name }}-gl-xml
      - if: ${{ steps.gl-xml.outputs.cache-hit != 'true' }}
        run: curl "https://github.com/KhronosGroup/OpenGL-Registry/raw/a959d350b027246018e18a0cf7e2144f8a113def/xml/gl.xml" -o gl.xml

      - run: zig build

      # check for runtime errors and panics
      - run: ./zig-out/bin/zglgen  --output ./zig-out/gen.zig gl.xml
      - run: zig test ./zig-out/gen.zig

  compile-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build -Doptimize=ReleaseSafe
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      - run: zig fmt --check src/*.zig
